#!/bin/bash

# You may need to also pass following arguments to the JVM

#  -XX:CICompilerCount=$NUM_CPUS
#  -XX:ConcGCThreads=$NUM_CPUS
#  -XX:ParallelGCThreads=$NUM_CPUS

LIMIT_ENV_VAR="LIMIT_JVM_NUM_CPUS"
SRC_DIR="$( dirname $0 )"
LIB_DIR="$( dirname $0 )/$( uname -i )"
LIB_NAME=libnumcpus.so
LIB_PATH="${LIB_DIR}/${LIB_NAME}"

if [ ! -e "${LIB_PATH}" ]; then
	echo "Compling CPU limit shared library (libnumcpus.so)..." 1>&2
	mkdir -pv "${LIB_DIR}"
	LIB_SRC="${SRC_DIR}/numcpus.c"
	gcc -O3 -fPIC -shared -Wl,-soname,libnumcpus.so -o "${LIB_PATH}" "${LIB_SRC}"
fi

if [ -z "${LIMIT_JVM_NUM_CPUS}" ] ; then
	LIMIT_JVM_NUM_CPUS="${1}"
	shift
fi
# Unused: -XX:-CMSConcurrentMTEnabled -XX:-UseConcMarkSweepGC -XX:-UseParNewGC

LD_PRELOAD="${LIBPATH} ${LD_PRELOAD}"

JAVA_TOOL_OPTIONS="${JAVA_TOOL_OPTIONS} -XX:CICompilerCount=${LIMIT_JVM_NUM_CPUS}"
JAVA_TOOL_OPTIONS="${JAVA_TOOL_OPTIONS} -XX:ParallelCMSThreads=${LIMIT_JVM_NUM_CPUS}"
JAVA_TOOL_OPTIONS="${JAVA_TOOL_OPTIONS} -XX:ParallelGCThreads=${LIMIT_JVM_NUM_CPUS}"
JAVA_TOOL_OPTIONS="${JAVA_TOOL_OPTIONS} ${JAVA_OPTS}"

export LIMIT_JVM_NUM_CPUS
export LD_PRELOAD
export JAVA_TOOL_OPTIONS

exec "$@"

